# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 47bdf77e40d9488d7e9c5e6c6ba588a1e40113315506b11005f7820ef57d171c6986ccf8001cfc82091dc3a5a349a8829172258d6e671aa8d272d16c28a778e8

test:
  secret_key_base: 0cbc770d32fc1975278335e2fbf9130fdf014f2ab228507c98478234e0e5675820ca28406ce40a6b4f32bdf8af4c8f5844002914b134fbe5b26faddafd94aaf4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
